//
//  MainModel.swift
//  MdEditor
//
//  Created by Александра Рязанова on 01.02.2024.
//  Copyright (c) 2024 SwiftbookTeam5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MainModel {

	enum Request {
		struct ItemSelected {
			let indexPath: IndexPath
		}
	}

	struct Response {
		let files: [File]
		let actions: [Action]

		struct File {
			let title: String
			let color: UIColor
		}

		enum Action {
			case new
			case open
			case about

			var title: String {
				switch self {
				case .new:
					return L10n.Main.Actions.new
				case .open:
					return L10n.Main.Actions.open
				case .about:
					return L10n.Main.Actions.about
				}
			}

			var image: UIImage {
				switch self {
				case .new:
					return Asset.Icons.file.image
				case .open:
					return Asset.Icons.openFolder.image
				case .about:
					return Asset.Icons.about.image
				}
			}
		}
	}

	struct ViewModel {

		/// Список секций для отображения
		let sections: [Section]

		struct Section {
			let type: SectionType
			let items: [Item]

			/// Перечисление представляющее тип конфигурирования секции
			enum SectionType {
				case horizontal
				case vertical
			}
		}

		/// Перечисление представляющее файлы и действия на экране
		enum Item {
			case file(File)
			case action(Action)
		}

		struct File {
			let title: String
			let color: UIColor
		}

		struct Action {
			let title: String
			let image: UIImage
		}
	}
}
