//
//  MainModel.swift
//  MdEditor
//
//  Created by Александра Рязанова on 01.02.2024.
//  Copyright (c) 2024 SwiftbookTeam5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

enum MainModel {

	enum MenuIdentifier {
		case openFile
		case newFile
		case showAbout

		var title: String {
			switch self {
			case .newFile:
				return L10n.Main.Menu.newFile
			case .openFile:
				return L10n.Main.Menu.openFile
			case .showAbout:
				return L10n.Main.Menu.about
			}
		}
	}

	enum Request {
		case menuItemSelected(indexPath: IndexPath)
		case recentFileSelected(indexPath: IndexPath)
	}

	struct Response {
		let recentFiles: [RecentFile]
		let menu: [MenuIdentifier]
	}

	struct ViewModel {

		/// Список секций для отображения
		let sections: [Section]

		struct Section {
			let type: SectionType
			let items: [Item]

			/// Перечисление представляющее тип конфигурирования секции
			enum SectionType {
				case horizontal
				case vertical
			}
		}

		/// Перечисление представляющее файлы и действия на экране
		enum Item {
			case menu(MenuItem)
			case file(RecentFile)
		}

		struct MenuItem {
			let title: String
			let item: MenuIdentifier
		}

		struct RecentFile {
			let previewText: String
			let fileName: String
		}
	}
}
