//
//  MainPresenter.swift
//  MdEditor
//
//  Created by Александра Рязанова on 01.02.2024.
//  Copyright (c) 2024 SwiftbookTeam5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol IMainPresenter {

	/// Отображение экрана со списком файлов и действий.
	/// - Parameter response: Подготовленные к отображению данные.
	func present(response: MainModel.Response)
}

final class MainPresenter: IMainPresenter {

	// MARK: - Dependencies

	private weak var viewController: IMainViewController! // swiftlint:disable:this implicitly_unwrapped_optional

	// MARK: - Initialization

	init(viewController: IMainViewController) {
		self.viewController = viewController
	}

	// MARK: - Internal methods

	/// Отображение экрана со списком файлов и действий.
	/// - Parameter response: Подготовленные к отображению данные.
	func present(response: MainModel.Response) {
		let sections = [
			MainModel.ViewModel.Section(
				type: .horizontal,
				items: mapFilesData(files: response.recentFiles)
			),
			MainModel.ViewModel.Section(
				type: .vertical,
				items: mapActionsData(menu: response.menu)
			)
		]

		viewController.render(viewModel: MainModel.ViewModel(sections: sections))
	}
}

// MARK: - Private methods

private extension MainPresenter {

	/// Мапинг файлов из бизнес-модели в файлы для отображения
	/// - Parameter files: Файлы для преобразования.
	/// - Returns: Преобразованный результат.
	func mapFilesData(files: [RecentFile]) -> [MainModel.ViewModel.Item] {
		files.map { mapFileData(file: $0) }
	}

	/// Мапинг одного файла из бизнес-модели в файл для отображения
	/// - Parameter file: Файл для преобразования.
	/// - Returns: Преобразованный результат.
	func mapFileData(file: RecentFile) -> MainModel.ViewModel.Item {
		let recentFile = MainModel.ViewModel.RecentFile(
			previewText: file.previewText,
			fileName: file.url.lastPathComponent
		)
		return MainModel.ViewModel.Item.file(recentFile)
	}

	/// Мапинг действий из бизнес-модели в действия для отображения
	/// - Parameter actions: Действия для преобразования.
	/// - Returns: Преобразованный результат.
	func mapActionsData(menu: [MainModel.MenuIdentifier]) -> [MainModel.ViewModel.Item] {
		menu.map { mapActionData(menu: $0) }
	}

	/// Мапинг одного действия из бизнес-модели в действие для отображения
	/// - Parameter task: Действие для преобразования.
	/// - Returns: Преобразованный результат.
	func mapActionData(menu: MainModel.MenuIdentifier) -> MainModel.ViewModel.Item {
		let menuItem = MainModel.ViewModel.MenuItem(
			title: menu.title,
			item: menu
		)
		return MainModel.ViewModel.Item.menu(menuItem)
	}
}
